Blinger/Blinger.MVC/Controllers/FlightsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Blinger.MVC.Data;
using Blinger.MVC.Services;
using Blinger.MVC.Models.FlightModels;

namespace Blinger.MVC.Controllers
{
    public class FlightsController : Controller
    {
        private readonly BlingerDbContext _context;
        private readonly FlightService _service;

        public FlightsController(BlingerDbContext context, FlightService service)
        {
            _context = context;
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            return View(_service.GetAll());
        }

        // GET: Flights/Create
        public IActionResult Create()
        {
            return View(new FlightCreateModel {AllAirlines=_context.Airline.ToList(), AllAirports=_context.Airports.ToList()});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FlightCreateModel flight)
        {
            if (ModelState.IsValid)
            {
                _service.Add(new Flight { AirlineName=flight.AirlineName, AirportOriginName=flight.AirportOriginName, AirportDestinationName=flight.AirportDestinationName, TakeOffDate=flight.TakeOffDate,LandingDate=flight.LandingDate, Row=(int)(flight.RowsBusiness+flight.RowsEconomy+flight.RowsFirst),Col=(int)(flight.ColsBusiness+flight.ColsEconomy+flight.ColsFirst)} );
                return RedirectToAction("CreateClass", "Seats", flight);
            }
            return View();
        }

       
    
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = _service.GetAll().FirstOrDefault(x=>x.Id==id);

            _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Search()
        {
            
            return View(new FlightSearchModel(null,null,null,_context.Airline.ToList(),_context.Airports.ToList(),new DateTime()));
        }
        public async Task<IActionResult> SearchFound(FlightSearchModel flightfound)
        {
            var flight = _service.FindFlight(flightfound).ToList();
            
            return View(_service.GetAllFoundFlights(flight));
        }
        private bool FlightExists(int id)
        {
            return _context.Flight.Any(e => e.Id == id);
        }
    }
}

Blinger/Blinger.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blinger.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
</head>
<body>
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a asp-area="" asp-controller="Home" asp-action="Index" id="div1">Home</a>
        <a asp-area="" asp-controller="Airports" asp-action="Index" id="div1">Airports</a>
        <a asp-area="" asp-controller="Airports" asp-action="IndexForDelete" id="div1"> - DeleteAirport</a>
        <a asp-area="" asp-controller="Airports" asp-action="Create" id="div1"> - CreateAirport</a>
        <a asp-area="" asp-controller="Airlines" asp-action="Index" id="div1">Airlines</a>
        <a asp-area="" asp-controller="Airlines" asp-action="IndexForDelete" id="div1"> - DeleteAirline</a>
        <a asp-area="" asp-controller="Airlines" asp-action="Create" id="div1"> - CreateAirline</a>
        <a asp-area="" asp-controller="Flights" asp-action="Index" id="div1">Flights</a>
        <a asp-area="" asp-controller="Flights" asp-action="Create" id="div1"> - CreateFlight</a>
    </div>
    <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Blinger - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>